### ISSUE TITLE
Gene order in datasets

### ISSUE THREAD

**Issue by niklas-w** [carlosp420/VoSeq#271]
The order of genes when making a dataset should be consistent, ie it should always be alphabetically ordered. Now it is almost so, but a number of genes end up going into the end of the dataset out of order. It is important to know the order of genes for manipulations of datasets after their generation in VoSeq.

**Comment by carlosp420** [comment]
fixed with 710776c1e6ccdf40e20df171f6bcb6504429e94f

Now the order is kept regardless of case. For example "ef1a" comes right after COI_end. Before it would go after RpS5.

DNA, ArgKin = 1-596
DNA, COI-begin = 597-1265
DNA, COI_end = 1266-2071
DNA, ef1a = 2072-3311
DNA, RpS2 = 3312-3722
DNA, RpS5 = 3723-4339
DNA, wingless = 4340-4739
