### ISSUE TITLE
voucher images not showing

### ISSUE THREAD

**Issue by mariespe** [carlosp420/VoSeq#343]
I can upload voucher images, but they don't show up. I only see an icon with a question mark, and when I click it I get a 404 not found error. Tried both Safari 9.1.1 and Firefox 45.0. "Photos_repository" in my config.json file is set to local. I tried to specify the location, but this didn't help.

Voseq is installed locally using the quick and easy install on my Macbook Pro with OSX 10.11.5

**Comment by carlosp420** [comment]
The was a bad configuration path for the server nginx. In order to correct this, you need update your local VoSeq with the latest version, then reload the vagrant files to update your nginx configuration and finally restart the server. Use these commands:
```
git pull origin master
vagrant reload --provision
vagrant ssh
sudo service nginx restart
```
This will fix the path to the images and you will see your own images if you upload them into your vouchers using the Admin interface.

If you want to fix the location of the example images of kittens of the test data just do:
```
cp /var/www/VoSeq/static/media/* /var/www/VoSeq/media/.
```
